using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TPIS.Model.Common
{
    public enum EleType
    {
        CFB,
        ECON,
        EVAP,
        EVAP2,
        Boiler,
        GasBoiler,
        SuperHeater,
        WaterSource,
        WaterPool,
        CoalSource,
        GasSoource,
        AshPool,
        Pipe,
        TeeGas,
        TeeFuel,
        TeeWater,
        TeeCoal,
        Compressor,
        Pump,
        GasTurbin,
        Controllingstage,
        Turbin,
        Laststage,
        Condenser,
        Deaerator,
        WaterHeater,
        PumpSteam,
        PTReducer,
        Fan,
        Chimney,
        ConTank,
        Generator,
        GasBurner,
        SurfaceHeatExchanger,
        ControlDot,
        GasHeatExchanger,
        ControlDotGas,
        SlagCooler,
        BagFilter,
        WaterTag,
        Throttle,
        GasMidTurbin,
        GasLastTurbin,
        MixedHeatExchanger,
        SteamHeader,
        WaterValve,
        TeeValve,
        SmallTurbin,
        FanSteam,
        Ejector,
        Thionizer,
        HeatSupply,
        Motor,
        TeePower,
        IterateDot,
        PipeEle,
        ControlValve,
        Calorifier,
        Airisland,
        GasHeater,
        IterateDotGas,
        None
    }
}
